---
- name: My Test Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: backup
      nxos_config:
        backup: yes
      register: backup_nxos_location
      when: ansible_network_os == 'nxos'

